import React, { useState } from "react";

/**
 *
 * @param {*} category - passing in the category of the current section
 * @param {*} addActivity - passing in the function to add the activity to the appropriate list
 * @returns Renders the input field and Add button for each activity section
 */
export default function ActivitiesInput({ category, addActivity }) {
  const [userInput, setUserInput] = useState("");

  /**
   * This sets the state of userInput to be whatever is currently in the text field.
   * @param {*} e - takes in the event object generated by the input changing
   */
  function handleChange(e) {
    setUserInput(e.target.value);
  }

  /**
   * This takes in the userInput and calls the addActivity function which adds it to the state.
   * It also resets the userInput/text field to be empty.
   * @param {*} userInput
   */
  function handleClick(userInput) {
    addActivity(userInput);
    setUserInput("");
  }

  /**
   * Here we render the input field and Add button.
   */
  return (
    <div className="input-field">
      <input
        className="activInput"
        id={`${category}-input`}
        value={userInput}
        onChange={handleChange}
      />
      <button
        className="activButton"
        onClick={() => {
          console.log(category);
          handleClick({ text: userInput, category: category });
        }}
      >
        Submit
      </button>
    </div>
  );
}
